version: '2'

services:

  git-server:
    image: git-server
    #build: .
    restart: always
    container_name: git-server
    ports:
      - "2222:22"
    volumes:
    - ~/git-server/keys:/git-server/keys
    - ~/git-server/repos:/git-server/repos

